# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AtomSeg_V1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import PyQt5

if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imagePath = QtWidgets.QTextEdit(self.centralwidget)
        self.imagePath.setEnabled(True)
        self.imagePath.setGeometry(QtCore.QRect(20, 30, 821, 31))
        self.imagePath.setObjectName("imagePath")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(880, 30, 91, 31))
        self.open.setObjectName("open")
        self.ori = QtWidgets.QLabel(self.centralwidget)
        self.ori.setGeometry(QtCore.QRect(20, 120, 410, 410))
        self.ori.setFrameShape(QtWidgets.QFrame.Box)
        self.ori.setText("")
        self.ori.setScaledContents(True)
        self.ori.setObjectName("ori")
        self.model_output = QtWidgets.QLabel(self.centralwidget)
        self.model_output.setGeometry(QtCore.QRect(440, 120, 410, 410))
        self.model_output.setFrameShape(QtWidgets.QFrame.Box)
        self.model_output.setText("")
        self.model_output.setScaledContents(True)
        self.model_output.setObjectName("model_output")
        self.preprocess = QtWidgets.QLabel(self.centralwidget)
        self.preprocess.setGeometry(QtCore.QRect(20, 540, 410, 410))
        self.preprocess.setFrameShape(QtWidgets.QFrame.Box)
        self.preprocess.setText("")
        self.preprocess.setScaledContents(True)
        self.preprocess.setObjectName("preprocess")
        self.detect_result = QtWidgets.QLabel(self.centralwidget)
        self.detect_result.setGeometry(QtCore.QRect(440, 540, 410, 410))
        self.detect_result.setFrameShape(QtWidgets.QFrame.Box)
        self.detect_result.setText("")
        self.detect_result.setScaledContents(True)
        self.detect_result.setObjectName("detect_result")
        self.modelPath = QtWidgets.QComboBox(self.centralwidget)
        self.modelPath.setGeometry(QtCore.QRect(20, 70, 821, 31))
        self.modelPath.setObjectName("modelPath")
        self.modelPath.addItem("")
        self.modelPath.addItem("")
        self.modelPath.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(870, 340, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.min_thre = QtWidgets.QSlider(self.centralwidget)
        self.min_thre.setGeometry(QtCore.QRect(870, 370, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.min_thre.setFont(font)
        self.min_thre.setMaximum(100)
        self.min_thre.setProperty("value", 30)
        self.min_thre.setOrientation(QtCore.Qt.Horizontal)
        self.min_thre.setObjectName("min_thre")
        self.max_thre = QtWidgets.QSlider(self.centralwidget)
        self.max_thre.setGeometry(QtCore.QRect(870, 420, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.max_thre.setFont(font)
        self.max_thre.setMinimum(100)
        self.max_thre.setMaximum(255)
        self.max_thre.setProperty("value", 150)
        self.max_thre.setOrientation(QtCore.Qt.Horizontal)
        self.max_thre.setObjectName("max_thre")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(870, 390, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.use_cuda = QtWidgets.QCheckBox(self.centralwidget)
        self.use_cuda.setGeometry(QtCore.QRect(860, 130, 131, 21))
        self.use_cuda.setChecked(True)
        self.use_cuda.setObjectName("use_cuda")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(880, 70, 91, 31))
        self.load.setObjectName("load")
        self.use_inter = QtWidgets.QCheckBox(self.centralwidget)
        self.use_inter.setGeometry(QtCore.QRect(860, 110, 131, 21))
        self.use_inter.setObjectName("use_inter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(870, 240, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.se_num = QtWidgets.QSlider(self.centralwidget)
        self.se_num.setGeometry(QtCore.QRect(870, 270, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.se_num.setFont(font)
        self.se_num.setMaximum(20)
        self.se_num.setOrientation(QtCore.Qt.Horizontal)
        self.se_num.setObjectName("se_num")
        self.circle_detect = QtWidgets.QPushButton(self.centralwidget)
        self.circle_detect.setGeometry(QtCore.QRect(880, 300, 91, 31))
        self.circle_detect.setObjectName("circle_detect")
        self.revert = QtWidgets.QPushButton(self.centralwidget)
        self.revert.setGeometry(QtCore.QRect(880, 500, 91, 31))
        self.revert.setObjectName("revert")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(880, 880, 91, 31))
        self.save.setObjectName("save")
        self.auto_save = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_save.setGeometry(QtCore.QRect(880, 920, 101, 21))
        self.auto_save.setObjectName("auto_save")
        self.imagePath.raise_()
        self.open.raise_()
        self.load.raise_()
        self.ori.raise_()
        self.model_output.raise_()
        self.preprocess.raise_()
        self.detect_result.raise_()
        self.revert.raise_()
        self.circle_detect.raise_()
        self.save.raise_()
        self.modelPath.raise_()
        self.se_num.raise_()
        self.use_inter.raise_()
        self.label.raise_()
        self.auto_save.raise_()
        self.label.raise_()
        self.use_inter.raise_()
        self.se_num.raise_()
        self.revert.raise_()
        self.auto_save.raise_()
        self.load.raise_()
        self.circle_detect.raise_()
        self.save.raise_()
        self.label_2.raise_()
        self.min_thre.raise_()
        self.max_thre.raise_()
        self.label_3.raise_()
        self.use_cuda.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Atom Segmentation"))
        self.open.setText(_translate("MainWindow", "OPEN"))
        self.modelPath.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.modelPath.setItemText(0, _translate("MainWindow", "Model 1"))
        self.modelPath.setItemText(1, _translate("MainWindow", "Model 2"))
        self.modelPath.setItemText(2, _translate("MainWindow", "Model 3"))
        self.label_2.setText(_translate("MainWindow", "Min Threshold"))
        self.label_3.setText(_translate("MainWindow", "Max Threshold"))
        self.use_cuda.setText(_translate("MainWindow", "Use CUDA"))
        self.load.setText(_translate("MainWindow", "LOAD"))
        self.use_inter.setText(_translate("MainWindow", "Use Interpolation"))
        self.label.setText(_translate("MainWindow", "Denoise Level"))
        self.circle_detect.setText(_translate("MainWindow", "DETECT"))
        self.revert.setText(_translate("MainWindow", "REVERT"))
        self.save.setText(_translate("MainWindow", "SAVE"))
        self.auto_save.setText(_translate("MainWindow", "Auto Save"))
