# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AtomSeg_V1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import PyQt5

if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 1077)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.use_inter = QtWidgets.QCheckBox(self.centralwidget)
        self.use_inter.setObjectName("use_inter")
        self.gridLayout.addWidget(self.use_inter, 0, 0, 1, 2)
        self.use_cuda = QtWidgets.QCheckBox(self.centralwidget)
        self.use_cuda.setChecked(True)
        self.use_cuda.setObjectName("use_cuda")
        self.gridLayout.addWidget(self.use_cuda, 0, 2, 1, 2)
        self.imagePath = QtWidgets.QTextEdit(self.centralwidget)
        self.imagePath.setEnabled(True)
        self.imagePath.setMaximumSize(QtCore.QSize(16777215, 31))
        self.imagePath.setReadOnly(True)
        self.imagePath.setObjectName("imagePath")
        self.gridLayout.addWidget(self.imagePath, 1, 0, 1, 7)
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setObjectName("open")
        self.gridLayout.addWidget(self.open, 1, 7, 1, 1)
        self.modelPath = QtWidgets.QComboBox(self.centralwidget)
        self.modelPath.setObjectName("modelPath")
        self.modelPath.addItem("")
        self.modelPath.addItem("")
        self.modelPath.addItem("")
        self.modelPath.addItem("")
        self.modelPath.addItem("")
        self.modelPath.addItem("")
        self.gridLayout.addWidget(self.modelPath, 2, 0, 1, 7)
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setObjectName("load")
        self.gridLayout.addWidget(self.load, 2, 7, 1, 1)
        self.circle_detect = QtWidgets.QPushButton(self.centralwidget)
        self.circle_detect.setObjectName("circle_detect")
        self.gridLayout.addWidget(self.circle_detect, 3, 0, 1, 1)
        self.revert = QtWidgets.QPushButton(self.centralwidget)
        self.revert.setObjectName("revert")
        self.gridLayout.addWidget(self.revert, 3, 3, 1, 1)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 3, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.se_num = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.se_num.setFont(font)
        self.se_num.setMaximum(20)
        self.se_num.setOrientation(QtCore.Qt.Horizontal)
        self.se_num.setObjectName("se_num")
        self.gridLayout.addWidget(self.se_num, 4, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 3, 1, 1)
        self.min_thre = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.min_thre.setFont(font)
        self.min_thre.setMaximum(100)
        self.min_thre.setProperty("value", 30)
        self.min_thre.setOrientation(QtCore.Qt.Horizontal)
        self.min_thre.setObjectName("min_thre")
        self.gridLayout.addWidget(self.min_thre, 4, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 5, 1, 1)
        self.max_thre = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.max_thre.setFont(font)
        self.max_thre.setMinimum(100)
        self.max_thre.setMaximum(255)
        self.max_thre.setProperty("value", 150)
        self.max_thre.setOrientation(QtCore.Qt.Horizontal)
        self.max_thre.setObjectName("max_thre")
        self.gridLayout.addWidget(self.max_thre, 4, 6, 1, 1)
        self.auto_save = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_save.setObjectName("auto_save")
        self.gridLayout.addWidget(self.auto_save, 4, 7, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.ori = QtWidgets.QLabel(self.splitter)
        self.ori.setFrameShape(QtWidgets.QFrame.Box)
        self.ori.setText("")
        self.ori.setScaledContents(True)
        self.ori.setObjectName("ori")
        self.model_output = QtWidgets.QLabel(self.splitter)
        self.model_output.setFrameShape(QtWidgets.QFrame.Box)
        self.model_output.setText("")
        self.model_output.setScaledContents(True)
        self.model_output.setObjectName("model_output")
        self.gridLayout.addWidget(self.splitter, 5, 0, 1, 7)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.preprocess = QtWidgets.QLabel(self.splitter_2)
        self.preprocess.setFrameShape(QtWidgets.QFrame.Box)
        self.preprocess.setText("")
        self.preprocess.setScaledContents(True)
        self.preprocess.setObjectName("preprocess")
        self.detect_result = QtWidgets.QLabel(self.splitter_2)
        self.detect_result.setFrameShape(QtWidgets.QFrame.Box)
        self.detect_result.setText("")
        self.detect_result.setScaledContents(True)
        self.detect_result.setObjectName("detect_result")
        self.gridLayout.addWidget(self.splitter_2, 6, 0, 1, 7)
        self.imagePath.raise_()
        self.open.raise_()
        self.load.raise_()
        self.ori.raise_()
        self.model_output.raise_()
        self.preprocess.raise_()
        self.detect_result.raise_()
        self.revert.raise_()
        self.circle_detect.raise_()
        self.save.raise_()
        self.modelPath.raise_()
        self.se_num.raise_()
        self.use_inter.raise_()
        self.label.raise_()
        self.auto_save.raise_()
        self.label.raise_()
        self.use_inter.raise_()
        self.revert.raise_()
        self.load.raise_()
        self.circle_detect.raise_()
        self.label_2.raise_()
        self.min_thre.raise_()
        self.max_thre.raise_()
        self.label_3.raise_()
        self.use_cuda.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Atom Segmentation"))
        self.use_inter.setText(_translate("MainWindow", "Use Interpolation"))
        self.use_cuda.setText(_translate("MainWindow", "Use CUDA"))
        self.open.setText(_translate("MainWindow", "OPEN"))
        self.modelPath.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.modelPath.setItemText(0, _translate("MainWindow", "Model 1"))
        self.modelPath.setItemText(1, _translate("MainWindow", "Model 2"))
        self.modelPath.setItemText(2, _translate("MainWindow", "Model 3"))
        self.modelPath.setItemText(3, _translate("MainWindow", "Model 4"))
        self.modelPath.setItemText(4, _translate("MainWindow", "Model 5"))
        self.modelPath.setItemText(5, _translate("MainWindow", "Model 6"))
        self.load.setText(_translate("MainWindow", "LOAD"))
        self.circle_detect.setText(_translate("MainWindow", "DETECT"))
        self.revert.setText(_translate("MainWindow", "REVERT"))
        self.save.setText(_translate("MainWindow", "SAVE"))
        self.label.setText(_translate("MainWindow", "Denoise Level"))
        self.label_2.setText(_translate("MainWindow", "Min Threshold"))
        self.label_3.setText(_translate("MainWindow", "Max Threshold"))
        self.auto_save.setText(_translate("MainWindow", "Auto Save"))

